name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

     - name: Navigate to project directory
       working-directory: Module00/ex03/
       run: pwd

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..
    
    - name: Build
      run: |
        cd build
        make
    
    - name: Run Tests
      run: |
        cd build
        ./PhoneBook < ../tests/test_input.txt
